version: 2.1
jobs:
  build:
    working_directory: ~/auth-service
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install dependencies
          command: "npm install"
      - run:
          name: Test
          command: "npm test"
workflows:
  build:
    jobs:
      - build
