version: 2.1
jobs:
  build:
    working_directory: ~/auth-service
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install dependencies
          command: "npm install"
      - run:
          name: Test
          command: "npm test"
    deploy:
      docker:
        - image: "circleci/node:12.16.1"
      steps:
        - checkout
        - run:
            name: "Deploy to Heroku"
            command: "git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master"
